import { useState } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Loader2, Globe, CheckCircle, AlertCircle, Copy, Trash2, ExternalLink, Code, CloudCog } from 'lucide-react';
import { apiRequest, queryClient } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';

interface CustomDomain {
  id: number;
  domain: string;
  deploymentSlug: string;
  verified: boolean;
  sslStatus: string;
  verificationToken: string;
  createdAt: string;
}

interface CloudflareInstructions {
  message: string;
  workerScript: string;
  jatevoHost: string;
  deploymentSlug: string;
  domain: string;
  steps: string[];
}

interface CustomDomainManagerProps {
  deploymentSlug: string;
  onDomainConnected?: () => void;
}

// Fallback script generator (used when viewing existing domains)
function generateFallbackWorkerScript(deploymentSlug: string, jatevoHost: string): string {
  return `// Cloudflare Worker for Jatevo Custom Domain
// Deployment: ${deploymentSlug}
// Generated by Jatevo Web Builder

const JATEVO_URL = "${jatevoHost}";
const DEPLOYMENT_SLUG = "${deploymentSlug}";

export default {
  async fetch(request) {
    const url = new URL(request.url);
    
    // Proxy all requests to the Jatevo deployment
    const targetUrl = \`\${JATEVO_URL}/sites/\${DEPLOYMENT_SLUG}\${url.pathname}\${url.search}\`;
    
    // Create new request with original headers
    const newRequest = new Request(targetUrl, {
      method: request.method,
      headers: request.headers,
      body: request.body,
      redirect: 'follow'
    });
    
    // Fetch from Jatevo and return response
    const response = await fetch(newRequest);
    
    // Clone response to modify headers if needed
    const newResponse = new Response(response.body, response);
    
    // Add CORS headers for assets
    newResponse.headers.set('Access-Control-Allow-Origin', '*');
    
    return newResponse;
  }
};`;
}

// Default Jatevo host - server will provide the correct one
const DEFAULT_JATEVO_HOST = 'https://jatevo.ai';

export function CustomDomainManager({ deploymentSlug, onDomainConnected }: CustomDomainManagerProps) {
  const [newDomain, setNewDomain] = useState('');
  const [showInstructions, setShowInstructions] = useState(false);
  const [copiedScript, setCopiedScript] = useState(false);
  const [serverWorkerScript, setServerWorkerScript] = useState<string | null>(null);
  const [serverJatevoHost, setServerJatevoHost] = useState<string>(DEFAULT_JATEVO_HOST);
  const { toast } = useToast();

  const { data: domainsData, isLoading } = useQuery<{ domains: CustomDomain[]; jatevoHost?: string }>({
    queryKey: ['/api/domains'],
    enabled: !!deploymentSlug,
  });

  const domains: CustomDomain[] = domainsData?.domains || [];
  const connectedDomain = domains.find(d => d.deploymentSlug === deploymentSlug);
  
  // Use jatevoHost from API response (for existing domains) or state (for newly created)
  const effectiveJatevoHost = domainsData?.jatevoHost || serverJatevoHost;

  const requestDomainMutation = useMutation({
    mutationFn: async (domain: string): Promise<{ success: boolean; customDomain: CustomDomain; cloudflareInstructions: CloudflareInstructions }> => {
      const response = await apiRequest('POST', '/api/domains', {
        domain,
        deploymentSlug,
      });
      return response.json();
    },
    onSuccess: (data) => {
      toast({
        title: 'Domain Registered',
        description: 'Follow the Cloudflare Workers setup instructions below.',
      });
      // Store the server-provided worker script
      if (data.cloudflareInstructions?.workerScript) {
        setServerWorkerScript(data.cloudflareInstructions.workerScript);
        setServerJatevoHost(data.cloudflareInstructions.jatevoHost || DEFAULT_JATEVO_HOST);
      }
      setShowInstructions(true);
      setNewDomain('');
      queryClient.invalidateQueries({ queryKey: ['/api/domains'] });
      onDomainConnected?.();
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.message || 'Failed to register domain',
        variant: 'destructive',
      });
    },
  });

  const markVerifiedMutation = useMutation({
    mutationFn: async (domainId: number): Promise<{ success: boolean }> => {
      const response = await apiRequest('POST', `/api/domains/${domainId}/mark-active`, {});
      return response.json();
    },
    onSuccess: () => {
      toast({
        title: 'Domain Activated',
        description: 'Your custom domain is now marked as active.',
      });
      queryClient.invalidateQueries({ queryKey: ['/api/domains'] });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.message || 'Failed to activate domain',
        variant: 'destructive',
      });
    },
  });

  const deleteDomainMutation = useMutation({
    mutationFn: async (domainId: number) => {
      await apiRequest('DELETE', `/api/domains/${domainId}`, undefined);
    },
    onSuccess: () => {
      toast({
        title: 'Domain Removed',
        description: 'Custom domain has been disconnected.',
      });
      queryClient.invalidateQueries({ queryKey: ['/api/domains'] });
      setShowInstructions(false);
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.message || 'Failed to remove domain',
        variant: 'destructive',
      });
    },
  });

  // Use server-provided script if available, otherwise generate fallback with correct host
  const workerScript = serverWorkerScript || generateFallbackWorkerScript(deploymentSlug, effectiveJatevoHost);

  const copyToClipboard = (text: string, isScript = false) => {
    navigator.clipboard.writeText(text);
    if (isScript) {
      setCopiedScript(true);
      setTimeout(() => setCopiedScript(false), 2000);
    }
    toast({
      title: 'Copied!',
      description: isScript ? 'Worker script copied to clipboard.' : 'Value copied to clipboard.',
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (newDomain.trim()) {
      requestDomainMutation.mutate(newDomain.trim().toLowerCase());
    }
  };

  if (isLoading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-8">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </CardContent>
      </Card>
    );
  }

  const CloudflareSetupInstructions = ({ domain }: { domain?: string }) => (
    <div className="space-y-4">
      <Alert className="border-blue-500/50 bg-blue-500/10">
        <CloudCog className="h-4 w-4 text-blue-500" />
        <AlertTitle className="text-blue-600">Cloudflare Workers Setup</AlertTitle>
        <AlertDescription className="mt-3 space-y-4">
          <p className="text-sm">Deploy this script to Cloudflare Workers to connect your custom domain:</p>
          
          {/* Worker Script */}
          <div className="relative">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-medium flex items-center gap-1">
                <Code className="h-4 w-4" />
                Worker Script
              </span>
              <Button
                size="sm"
                variant={copiedScript ? "default" : "outline"}
                onClick={() => copyToClipboard(workerScript, true)}
                data-testid="button-copy-script"
              >
                {copiedScript ? (
                  <>
                    <CheckCircle className="h-3 w-3 mr-1" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="h-3 w-3 mr-1" />
                    Copy Script
                  </>
                )}
              </Button>
            </div>
            <pre className="p-4 bg-zinc-900 text-zinc-100 rounded-lg text-xs overflow-x-auto max-h-64 overflow-y-auto">
              <code>{workerScript}</code>
            </pre>
          </div>

          {/* Step by step instructions */}
          <div className="space-y-3 mt-4">
            <p className="text-sm font-medium">Setup Steps:</p>
            <ol className="list-decimal list-inside space-y-2 text-sm">
              <li className="pl-2">
                <span className="font-medium">Go to Cloudflare Dashboard</span>
                <a 
                  href="https://dash.cloudflare.com/?to=/:account/workers-and-pages" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="ml-2 text-blue-500 hover:underline inline-flex items-center"
                >
                  Open Cloudflare <ExternalLink className="h-3 w-3 ml-1" />
                </a>
              </li>
              <li className="pl-2">
                <span className="font-medium">Create a new Worker</span>
                <span className="text-muted-foreground ml-1">→ Workers & Pages → Create → Create Worker</span>
              </li>
              <li className="pl-2">
                <span className="font-medium">Replace the code</span>
                <span className="text-muted-foreground ml-1">→ Paste the script above → Deploy</span>
              </li>
              <li className="pl-2">
                <span className="font-medium">Add Custom Domain</span>
                <span className="text-muted-foreground ml-1">→ Worker Settings → Triggers → Add Custom Domain</span>
              </li>
              <li className="pl-2">
                <span className="font-medium">Enter your domain</span>
                <span className="text-muted-foreground ml-1">→ {domain || 'yourdomain.com'} → Add</span>
              </li>
            </ol>
          </div>

          <div className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-lg mt-3">
            <p className="text-sm text-amber-600 dark:text-amber-400">
              <strong>Note:</strong> Your domain must be added to Cloudflare first. 
              Cloudflare will automatically handle SSL certificates and DNS routing.
            </p>
          </div>
        </AlertDescription>
      </Alert>
    </div>
  );

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Globe className="h-5 w-5" />
          Custom Domain
        </CardTitle>
        <CardDescription>
          Connect your own domain using Cloudflare Workers for professional branding
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {connectedDomain ? (
          <div className="space-y-4">
            <div className="flex items-center justify-between p-4 border rounded-lg bg-muted/50">
              <div className="flex items-center gap-3">
                <Globe className="h-5 w-5 text-primary" />
                <div>
                  <p className="font-medium">{connectedDomain.domain}</p>
                  <p className="text-sm text-muted-foreground">
                    Connected to {connectedDomain.deploymentSlug}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                {connectedDomain.verified ? (
                  <Badge className="bg-green-500 hover:bg-green-600">
                    <CheckCircle className="h-3 w-3 mr-1" />
                    Active
                  </Badge>
                ) : (
                  <Badge variant="secondary" className="bg-yellow-500/20 text-yellow-600">
                    <AlertCircle className="h-3 w-3 mr-1" />
                    Setup Required
                  </Badge>
                )}
                {!connectedDomain.verified && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => markVerifiedMutation.mutate(connectedDomain.id)}
                    disabled={markVerifiedMutation.isPending}
                    data-testid="button-mark-active"
                  >
                    {markVerifiedMutation.isPending ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <CheckCircle className="h-4 w-4" />
                    )}
                    <span className="ml-1">Mark Active</span>
                  </Button>
                )}
                <Button
                  size="sm"
                  variant="ghost"
                  className="text-destructive hover:text-destructive"
                  onClick={() => deleteDomainMutation.mutate(connectedDomain.id)}
                  disabled={deleteDomainMutation.isPending}
                  data-testid="button-remove-domain"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </div>

            {!connectedDomain.verified && (
              <CloudflareSetupInstructions domain={connectedDomain.domain} />
            )}

            {connectedDomain.verified && (
              <Alert className="border-green-500/50 bg-green-500/10">
                <CheckCircle className="h-4 w-4 text-green-500" />
                <AlertTitle className="text-green-600">Domain Active</AlertTitle>
                <AlertDescription>
                  <p>Your site is now accessible at:</p>
                  <a
                    href={`https://${connectedDomain.domain}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1 text-primary hover:underline mt-1"
                  >
                    https://{connectedDomain.domain}
                    <ExternalLink className="h-3 w-3" />
                  </a>
                </AlertDescription>
              </Alert>
            )}

            {/* Always show script for reference */}
            {connectedDomain.verified && (
              <details className="mt-4">
                <summary className="cursor-pointer text-sm text-muted-foreground hover:text-foreground">
                  View Cloudflare Worker Script
                </summary>
                <div className="mt-2">
                  <CloudflareSetupInstructions domain={connectedDomain.domain} />
                </div>
              </details>
            )}
          </div>
        ) : (
          <div className="space-y-4">
            <form onSubmit={handleSubmit} className="flex gap-2">
              <Input
                type="text"
                placeholder="example.com or www.example.com"
                value={newDomain}
                onChange={(e) => setNewDomain(e.target.value)}
                className="flex-1"
                data-testid="input-custom-domain"
              />
              <Button
                type="submit"
                disabled={!newDomain.trim() || requestDomainMutation.isPending}
                data-testid="button-connect-domain"
              >
                {requestDomainMutation.isPending ? (
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                ) : null}
                Connect
              </Button>
            </form>

            {showInstructions && (
              <CloudflareSetupInstructions domain={newDomain} />
            )}

            <div className="text-sm text-muted-foreground">
              <p className="font-medium mb-1">Requirements:</p>
              <ul className="list-disc list-inside space-y-1">
                <li>Your domain must be added to Cloudflare</li>
                <li>A Cloudflare account (free tier works)</li>
                <li>About 5 minutes to set up</li>
              </ul>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
