import React, { useEffect, useState } from 'react';

interface GenerationStatusProps {
  status: string[];
  processingItem?: string;
  percentComplete?: number;
}

export function GenerationStatus({ 
  status, 
  processingItem, 
  percentComplete 
}: GenerationStatusProps) {
  // Keep status component visible for at least some time even if percentComplete reaches 100%
  const [showProgress, setShowProgress] = useState(true);
  
  // Used for smoother progress animation
  const [displayedPercent, setDisplayedPercent] = useState(0);
  
  // When percentComplete changes, animate the progress smoothly
  useEffect(() => {
    // If we have a valid percent value
    if (typeof percentComplete === 'number') {
      // If the new percent is significantly different, animate to it
      if (Math.abs(percentComplete - displayedPercent) > 3) {
        // Small increments for smoother animation
        const step = percentComplete > displayedPercent ? 3 : -3;
        const timer = setTimeout(() => {
          setDisplayedPercent(prev => {
            // Move toward the target percentComplete
            const next = prev + step;
            // Make sure we don't overshoot the target
            if (step > 0) {
              return Math.min(next, percentComplete);
            } else {
              return Math.max(next, percentComplete);
            }
          });
        }, 100);
        return () => clearTimeout(timer);
      }
    }
  }, [percentComplete, displayedPercent]);
  
  // When percentComplete reaches 100, delay hiding the progress bar
  useEffect(() => {
    if (percentComplete && percentComplete >= 100) {
      // Keep showing progress bar for a while even after reaching 100%
      const timer = setTimeout(() => {
        setShowProgress(false);
      }, 2000);
      return () => clearTimeout(timer);
    } else {
      setShowProgress(true);
    }
  }, [percentComplete]);

  // Filter out duplicate status messages
  const uniqueStatus = status.reduce((acc, current, index) => {
    // Skip if this message is identical to the previous message
    if (index > 0 && current === status[index - 1]) {
      return acc;
    }
    return [...acc, current];
  }, [] as string[]);

  return (
    <div className="bg-blue-950 text-gray-200 rounded-lg p-4 text-sm font-mono overflow-hidden">
      <div className="flex items-center mb-1">
        <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        <span className="text-white">Generating with AI Accelerate</span>
      </div>
      
      {processingItem && (
        <div className="mb-1 text-gray-300">
          Processing: {processingItem}
        </div>
      )}
      
      {uniqueStatus.map((line, index) => {
        // Check if the line contains a checkmark, success message, or complete message
        const isSuccess = line.includes('✅') 
          || line.toLowerCase().includes('success') 
          || line.includes('Content successfully generated');
        
        // Check if the line contains an error or warning
        const isError = line.includes('⚠️') || line.toLowerCase().includes('error');
        
        // Check if line has completed status (100%)
        const isCompleted = line.includes('100% complete');
        
        // Check if line is empty (used for spacing)
        const isEmpty = line.trim() === '';
        
        // Special styling for completion message
        const completionMessage = line.includes('Content successfully generated by AI Accelerate LLM Inference');
        
        if (isEmpty) {
          return <div key={index} className="h-2"></div>; // Empty spacer
        }
        
        return (
          <div 
            key={index} 
            className={`mb-1 ${isSuccess ? 'text-green-400 font-medium' : ''} ${isError ? 'text-yellow-400' : ''} ${isCompleted ? 'text-blue-300' : ''}`}
            style={completionMessage ? { 
              fontSize: '1.05em', 
              letterSpacing: '0.02em',
              padding: '4px 8px',
              backgroundColor: 'rgba(0, 255, 0, 0.1)',
              borderRadius: '4px',
              borderLeft: '3px solid #34d399',
              marginTop: '6px',
              marginBottom: '6px'
            } : isSuccess ? { 
              fontSize: '0.95em', 
              letterSpacing: '0.02em' 
            } : {}}
          >
            {line}
          </div>
        );
      })}
      
      {/* Always show the progress bar during generation regardless of percentComplete */}
      <div className="mt-2">
        <div className="flex items-center">
          <div className="h-2 bg-blue-900 rounded-full w-full">
            <div 
              className="h-2 bg-blue-400 rounded-full transition-all duration-500 ease-out" 
              style={{ width: `${Math.min(displayedPercent, 100)}%` }}
            ></div>
          </div>
          <span className="ml-2 text-blue-300 min-w-[4rem] text-right">
            {Math.min(Math.round(displayedPercent), 100)}% 
          </span>
        </div>
      </div>
    </div>
  );
}